In changelog entry display also the last changed date of debian directory
git-svn-id: https://voikko.svn.sourceforge.net/svnroot/voikko/trunk/debian@1397 ee56993d-3414-0410-8ed4-8136e77a0dd8

diff --git a/tools/makevoikkodeb b/tools/makevoikkodeb
--- a/tools/makevoikkodeb
+++ b/tools/makevoikkodeb
@@ -45,32 +45,39 @@ uncompress_archive() { #{{{1
 		echo "ERROR: File not found: $filename"
 		exit 1
 	fi
-	if file "$filename" | grep 'gzip compressed data' >/dev/null; then
-		tar --extract --verbose --gzip --file "$filename" --show-transformed --transform=s,^[^/]*,$component, || exit 1
-	elif file "$filename" | grep 'bzip2 compressed data' >/dev/null; then
-		check_package bzip2
-		tar --extract --verbose --bzip2 --file "$filename" --show-transformed --transform=s,^[^/]*,$component, || exit 1
-	elif file "$filename" | grep 'tar archive' >/dev/null; then
-		tar --extract --verbose --file "$filename" --show-transformed --transform=s,^[^/]*,$component, || exit 1
-	else
-		echo "ERROR: Unknown archive format in file $filename"
-		exit 1
-	fi
+	case $(file "$filename") in
+		*gzip\ compressed\ data*)
+			tar --extract --verbose --gzip --file "$filename" --show-transformed --transform=s,^[^/]*,$component, || exit 1
+			;;
+		*bzip2\ compressed\ data*)
+			check_package bzip2
+			tar --extract --verbose --bzip2 --file "$filename" --show-transformed --transform=s,^[^/]*,$component, || exit 1
+			;;
+		*tar\ archive*)
+			tar --extract --verbose --file "$filename" --show-transformed --transform=s,^[^/]*,$component, || exit 1
+			;;
+		*)
+			echo "ERROR: Unknown archive format (gzip and bzip2 compressed tar archives are supported)"
+			file "$filename"
+			exit 1
+			;;
+	esac
 	}
 
 update_changelog() { #{{{1
-	local svn_revision svn_last_changed_deb svn_last_changed_source package version changelognew
+	local svn_revision svn_last_changed_debian svn_last_changed_source package version changelognew
 	svn_revision=$(svn info debian 2>/dev/null | awk '/^Revision:/ {print $2}')
 	svn_last_changed_source=$(svn info 2>/dev/null | awk '/^Last Changed Date:/ {printf "%s %s %s\n",$4,$5,$6}')
-	#svn_last_changed_debian=$(svn info debian 2>/dev/null | awk '/^Last Changed Date:/ {printf "%s %s %s\n",$4,$5,$6}')
+	svn_last_changed_debian=$(svn info debian 2>/dev/null | awk '/^Last Changed Date:/ {printf "%s %s %s\n",$4,$5,$6}')
 	package=$(dpkg-parsechangelog | awk '/^Source:/ {print $2}')
 	version=$(dpkg-parsechangelog | awk '/^Version:/ {print $2}')
 	version=${version%-*}
 	version=${version%+svn*}
 	changelognew=debian/changelog.new
 	echo -e "$package (${version}+svn${svn_revision}-1) unstable; urgency=low\n" >$changelognew
-	echo -e "  * Upstream development snapshot" >>$changelognew
-	echo -e "    Source tree last changed: ${svn_last_changed_source:-(no info)}\n" >>$changelognew
+	echo -e "  * Upstream development snapshot. Last changes:" >>$changelognew
+	echo -e "    Source tree: ${svn_last_changed_source:-(no info)}" >>$changelognew
+	echo -e "    Debian data: ${svn_last_changed_debian:-(no info)}\n" >>$changelognew
 	echo -e " -- ${DEBFULLNAME:-Nobody} <${DEBEMAIL:-nobody@invalid}>  $(date -R)\n" >>$changelognew
 	cat debian/changelog >>$changelognew
 	mv $changelognew debian/changelog
@@ -184,7 +191,7 @@ Examples:
 EOF
 	}
 
-#{{{1 Parse command line parameters
+#{{{1 Parse command line
 case $component in
 	libvoikko|ooovoikko|tmispell|suomimalaga)
 		check_package build-essential fakeroot subversion
