Check if URL is missing
git-svn-id: https://voikko.svn.sourceforge.net/svnroot/voikko/trunk/debian@1358 ee56993d-3414-0410-8ed4-8136e77a0dd8

diff --git a/tools/makevoikkodeb b/tools/makevoikkodeb
--- a/tools/makevoikkodeb
+++ b/tools/makevoikkodeb
@@ -23,6 +23,7 @@ get_svn() { #{{{1
 
 get_url() { #{{{1 
 	local url="$1"
+	if [ ! $url ]; then echo "ERROR: URL is missing"; exit 1; fi
 	wget "$url" || exit 1
 	}
 
